condense_wildcard_suffixes = true
edition = "2021"
fn_call_width = 80
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
max_width = 140
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
